#!/bin/bash

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
	DIRTY="-dirty"
fi

COMMIT=$(git rev-parse --short HEAD)
GIT_TAG=$(git tag -l --contains HEAD | head -n 1)
GIT_NB_COMMIT_SINCE_LAST_TAG=`git rev-list $(git describe --tags 2> /dev/null | awk -F'-' '{ print $1 }')..HEAD --count`

if [ -z "$VERSION" ]; then
	if [[ -z "$DIRTY" && -n "$GIT_TAG" ]]; then
		VERSION=$GIT_TAG
	else
		VERSION="${COMMIT}${DIRTY}"
	fi
fi

RELEASE=${GIT_NB_COMMIT_SINCE_LAST_TAG}
if [ ${RELEASE} -eq 0 ]; then
	RELEASE="1"
fi

export COMMIT VERSION RELEASE
